spring:
  application:
    name: "client-manager"
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: client-manager-pool
  jpa:
    hibernate:
      ddl-auto: update # ou validate, create-drop, none, dependendo da tua estratégia
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always